### ISSUE TITLE
create-react-sampleのyarn testがコケる

### ISSUE THREAD

**Issue by 0num4** [0num4/nestjs-dynamo-graphsql-sls-sample#7]
多分initしたときにjestがバグってたのが起因している。
TypeError: babelJest.createTransformer is not a function

```
$ react-scripts build
Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  50.53 KB       build\static\js\2.cc09c035.chunk.js
  1.64 KB        build\static\js\3.47675f48.chunk.js
  1.17 KB        build\static\js\runtime-main.c1213aee.js
  911 B (+13 B)  build\static\js\main.e1a4cd3d.chunk.js
  557 B          build\static\css\main.5739ad41.chunk.css

The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
You may serve it with a static server:

  yarn global add serve
  serve -s build

Find out more about deployment here:

  https://cra.link/deployment
No tests found related to files changed since last commit.
Press `a` to run all tests, or run Jest with `--watchAll`.

Watch Usage
 FAIL  src/App.test.tsx
  ● Test suite failed to run

    TypeError: babelJest.createTransformer is not a function

      at Object.<anonymous> (node_modules/react-scripts/config/jest/babelTransform.js:26:28)
      at ScriptTransformer._getTransformer (node_modules/@jest/transform/build/ScriptTransformer.js:347:21)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:427:28)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:569:40)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        6.567 s
Ran all test suites.

Watch Usage: Press w to show more.
```

**Comment by 0num4** [comment]
fixed
